# Gradient Boost Classifier

In [68]:
import numpy as np
import pandas as pd

In [10]:
df=pd.read_csv('brca.csv')
df.head()

,Unnamed: 0,x.radius_mean,x.texture_mean,x.perimeter_mean,x.area_mean,x.smoothness_mean,x.compactness_mean,x.concavity_mean,x.concave_pts_mean,x.symmetry_mean,...,x.texture_worst,x.perimeter_worst,x.area_worst,x.smoothness_worst,x.compactness_worst,x.concavity_worst,x.concave_pts_worst,x.symmetry_worst,x.fractal_dim_worst,y
0,1,13.540,14.36,87.46,566.3,0.09779,0.08129,0.06664,0.047810,0.1885,...,19.26,99.70,711.2,0.14400,0.17730,0.23900,0.12880,0.2977,0.07259,B
1,2,13.080,15.71,85.63,520.0,0.10750,0.12700,0.04568,0.031100,0.1967,...,20.49,96.09,630.5,0.13120,0.27760,0.18900,0.07283,0.3184,0.08183,B
2,3,9.504,12.44,60.34,273.9,0.10240,0.06492,0.02956,0.020760,0.1815,...,15.66,65.13,314.9,0.13240,0.11480,0.08867,0.06227,0.2450,0.07773,B
3,4,13.030,18.42,82.61,523.8,0.08983,0.03766,0.02562,0.029230,0.1467,...,22.81,84.46,545.9,0.09701,0.04619,0.04833,0.05013,0.1987,0.06169,B
4,5,8.196,16.84,51.71,201.9,0.08600,0.05943,0.01588,0.005917,0.1769,...,21.96,57.26,242.2,0.12970,0.13570,0.06880,0.02564,0.3105,0.07409,B

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           569 non-null    int64
 1   x.radius_mean        569 non-null    float64
 2   x.texture_mean       569 non-null    float64
 3   x.perimeter_mean     569 non-null    float64
 4   x.area_mean          569 non-null    float64
 5   x.smoothness_mean    569 non-null    float64
 6   x.compactness_mean   569 non-null    float64
 7   x.concavity_mean     569 non-null    float64
 8   x.concave_pts_mean   569 non-null    float64
 9   x.symmetry_mean      569 non-null    float64
 10  x.fractal_dim_mean   569 non-null    float64
 11  x.radius_se          569 non-null    float64
 12  x.texture_se         569 non-null    float64
 13  x.perimeter_se       569 non-null    float64
 14  x.area_se            569 non-null    float64
 15  x.smoothness_se      569 non-null    float64
 16  x.compactness_se     569 non-null    float64
 17  x.concavity_se       569 non-null    float64
 18  x.concave_pts_se     569 non-null    float64
 19  x.symmetry_se        569 non-null    float64
 20  x.fractal_dim_se     569 non-null    float64
 21  x.radius_worst       569 non-null    float64
 22  x.texture_worst      569 non-null    float64
 23  x.perimeter_worst    569 non-null    float64
 24  x.area_worst         569 non-null    float64
 25  x.smoothness_worst   569 non-null    float64
 26  x.compactness_worst  569 non-null    float64
 27  x.concavity_worst    569 non-null    float64
 28  x.concave_pts_worst  569 non-null    float64
 29  x.symmetry_worst     569 non-null    float64
 30  x.fractal_dim_worst  569 non-null    float64
 31  y                    569 non-null    object
dtypes: float64(30), int64(1), object(1)
memory usage: 142.4+ KB

In [15]:
df.drop('Unnamed: 0',axis=1,inplace=True)

In [16]:
df.isnull().sum()

x.radius_mean          0
x.texture_mean         0
x.perimeter_mean       0
x.area_mean            0
x.smoothness_mean      0
x.compactness_mean     0
x.concavity_mean       0
x.concave_pts_mean     0
x.symmetry_mean        0
x.fractal_dim_mean     0
x.radius_se            0
x.texture_se           0
x.perimeter_se         0
x.area_se              0
x.smoothness_se        0
x.compactness_se       0
x.concavity_se         0
x.concave_pts_se       0
x.symmetry_se          0
x.fractal_dim_se       0
x.radius_worst         0
x.texture_worst        0
x.perimeter_worst      0
x.area_worst           0
x.smoothness_worst     0
x.compactness_worst    0
x.concavity_worst      0
x.concave_pts_worst    0
x.symmetry_worst       0
x.fractal_dim_worst    0
y                      0
dtype: int64

In [17]:
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()
df['y']=label.fit_transform(df['y'])

In [18]:
df.head()

,x.radius_mean,x.texture_mean,x.perimeter_mean,x.area_mean,x.smoothness_mean,x.compactness_mean,x.concavity_mean,x.concave_pts_mean,x.symmetry_mean,x.fractal_dim_mean,...,x.texture_worst,x.perimeter_worst,x.area_worst,x.smoothness_worst,x.compactness_worst,x.concavity_worst,x.concave_pts_worst,x.symmetry_worst,x.fractal_dim_worst,y
0,13.540,14.36,87.46,566.3,0.09779,0.08129,0.06664,0.047810,0.1885,0.05766,...,19.26,99.70,711.2,0.14400,0.17730,0.23900,0.12880,0.2977,0.07259,0
1,13.080,15.71,85.63,520.0,0.10750,0.12700,0.04568,0.031100,0.1967,0.06811,...,20.49,96.09,630.5,0.13120,0.27760,0.18900,0.07283,0.3184,0.08183,0
2,9.504,12.44,60.34,273.9,0.10240,0.06492,0.02956,0.020760,0.1815,0.06905,...,15.66,65.13,314.9,0.13240,0.11480,0.08867,0.06227,0.2450,0.07773,0
3,13.030,18.42,82.61,523.8,0.08983,0.03766,0.02562,0.029230,0.1467,0.05863,...,22.81,84.46,545.9,0.09701,0.04619,0.04833,0.05013,0.1987,0.06169,0
4,8.196,16.84,51.71,201.9,0.08600,0.05943,0.01588,0.005917,0.1769,0.06503,...,21.96,57.26,242.2,0.12970,0.13570,0.06880,0.02564,0.3105,0.07409,0

In [19]:
X=df.drop('y',axis=1)
y=df['y']

In [20]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25)

In [22]:
from sklearn.model_selection import KFold
fold=KFold(n_splits=100,random_state=42,shuffle=True)

In [28]:
from sklearn.ensemble import GradientBoostingClassifier
model = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, random_state=42)

In [29]:
from sklearn.model_selection import cross_val_score
cv=cross_val_score(model,X_train,y_train,cv=fold)

for i in range(len(cv)):
    print("model",i,'accuracy:',cv[i])

model 0 accuracy: 1.0
model 1 accuracy: 1.0
model 2 accuracy: 1.0
model 3 accuracy: 1.0
model 4 accuracy: 1.0
model 5 accuracy: 0.8
model 6 accuracy: 1.0
model 7 accuracy: 1.0
model 8 accuracy: 1.0
model 9 accuracy: 0.8
model 10 accuracy: 1.0
model 11 accuracy: 1.0
model 12 accuracy: 1.0
model 13 accuracy: 1.0
model 14 accuracy: 1.0
model 15 accuracy: 1.0
model 16 accuracy: 0.8
model 17 accuracy: 1.0
model 18 accuracy: 0.8
model 19 accuracy: 1.0
model 20 accuracy: 1.0
model 21 accuracy: 1.0
model 22 accuracy: 0.8
model 23 accuracy: 1.0
model 24 accuracy: 1.0
model 25 accuracy: 0.8
model 26 accuracy: 1.0
model 27 accuracy: 0.75
model 28 accuracy: 1.0
model 29 accuracy: 1.0
model 30 accuracy: 0.75
model 31 accuracy: 1.0
model 32 accuracy: 0.75
model 33 accuracy: 1.0
model 34 accuracy: 0.75
model 35 accuracy: 1.0
model 36 accuracy: 0.75
model 37 accuracy: 1.0
model 38 accuracy: 1.0
model 39 accuracy: 0.75
model 40 accuracy: 0.75
model 41 accuracy: 0.75
model 42 accuracy: 1.0
model 43 accuracy: 1.0
model 44 accuracy: 1.0
model 45 accuracy: 1.0
model 46 accuracy: 0.75
model 47 accuracy: 1.0
model 48 accuracy: 1.0
model 49 accuracy: 1.0
model 50 accuracy: 1.0
model 51 accuracy: 1.0
model 52 accuracy: 1.0
model 53 accuracy: 1.0
model 54 accuracy: 1.0
model 55 accuracy: 1.0
model 56 accuracy: 1.0
model 57 accuracy: 1.0
model 58 accuracy: 1.0
model 59 accuracy: 1.0
model 60 accuracy: 1.0
model 61 accuracy: 1.0
model 62 accuracy: 0.5
model 63 accuracy: 1.0
model 64 accuracy: 1.0
model 65 accuracy: 1.0
model 66 accuracy: 1.0
model 67 accuracy: 1.0
model 68 accuracy: 1.0
model 69 accuracy: 1.0
model 70 accuracy: 1.0
model 71 accuracy: 1.0
model 72 accuracy: 0.75
model 73 accuracy: 1.0
model 74 accuracy: 1.0
model 75 accuracy: 1.0
model 76 accuracy: 1.0
model 77 accuracy: 1.0
model 78 accuracy: 1.0
model 79 accuracy: 1.0
model 80 accuracy: 1.0
model 81 accuracy: 1.0
model 82 accuracy: 1.0
model 83 accuracy: 1.0
model 84 accuracy: 1.0
model 85 accuracy: 1.0
model 86 accuracy: 1.0
model 87 accuracy: 1.0
model 88 accuracy: 0.75
model 89 accuracy: 1.0
model 90 accuracy: 1.0
model 91 accuracy: 1.0
model 92 accuracy: 1.0
model 93 accuracy: 1.0
model 94 accuracy: 1.0
model 95 accuracy: 1.0
model 96 accuracy: 1.0
model 97 accuracy: 1.0
model 98 accuracy: 0.75
model 99 accuracy: 0.75

In [30]:
from sklearn.metrics import classification_report
model.fit(X_train,y_train)
y_pred=model.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.95      0.99      0.97        88
           1       0.98      0.91      0.94        55

    accuracy                           0.96       143
   macro avg       0.96      0.95      0.96       143
weighted avg       0.96      0.96      0.96       143

# Gradient Regressor

In [31]:
df=pd.read_csv('Life Expectancy.csv')
df.head()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2938 entries, 0 to 2937
Data columns (total 22 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Country                          2938 non-null   object
 1   Year                             2938 non-null   int64
 2   Status                           2938 non-null   object
 3   Life expectancy                  2928 non-null   float64
 4   Adult Mortality                  2928 non-null   float64
 5   infant deaths                    2938 non-null   int64
 6   Alcohol                          2744 non-null   float64
 7   percentage expenditure           2938 non-null   float64
 8   Hepatitis B                      2385 non-null   float64
 9   Measles                          2938 non-null   int64
 10   BMI                             2904 non-null   float64
 11  under-five deaths                2938 non-null   int64
 12  Polio                            2919 non-null   float64
 13  Total expenditure                2712 non-null   float64
 14  Diphtheria                       2919 non-null   float64
 15   HIV/AIDS                        2938 non-null   float64
 16  GDP                              2490 non-null   float64
 17  Population                       2286 non-null   float64
 18   thinness  1-19 years            2904 non-null   float64
 19   thinness 5-9 years              2904 non-null   float64
 20  Income composition of resources  2771 non-null   float64
 21  Schooling                        2775 non-null   float64
dtypes: float64(16), int64(4), object(2)
memory usage: 505.1+ KB

In [33]:
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()
df['Country']=label.fit_transform(df['Country'])
df['Year']=label.fit_transform(df['Year'])
df['Status']=label.fit_transform(df['Status'])

In [34]:
df.head()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,0,15,1,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,0,14,1,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,0,13,1,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,0,12,1,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,0,11,1,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

In [39]:
df['Country'].unique()

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  44,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,
        38,  39,  40,  41,  42,  43,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
       182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192])

In [41]:
df['Alcohol'].unique()

array([0.01, 0.03, 0.02, ..., 2.44, 3.56, 4.57])

In [42]:
df.isnull().sum()

Country                              0
Year                                 0
Status                               0
Life expectancy                     10
Adult Mortality                     10
infant deaths                        0
Alcohol                            194
percentage expenditure               0
Hepatitis B                        553
Measles                              0
 BMI                                34
under-five deaths                    0
Polio                               19
Total expenditure                  226
Diphtheria                          19
 HIV/AIDS                            0
GDP                                448
Population                         652
 thinness  1-19 years               34
 thinness 5-9 years                 34
Income composition of resources    167
Schooling                          163
dtype: int64

In [43]:
df['Hepatitis B'].unique()

array([65., 62., 64., 67., 68., 66., 63., 99., 98., 97., 96., 95., 94.,
       91.,  9.,  8., 83., 81., nan, 77., 75., 72., 61., 69., 73., 85.,
       84., 88., 93., 89., 78., 55., 92., 86., 44., 33., 74., 52., 49.,
        5., 51., 21., 45., 11., 87., 18., 56.,  7.,  6., 76., 82., 79.,
       15., 36., 48.,  1.,  4., 42., 28., 14., 47., 23., 46., 37., 39.,
       24., 17., 27., 25., 16.,  2., 35., 29., 26., 54., 57., 38., 59.,
       71., 43., 58., 41., 31., 12., 32., 22., 53., 19.])

In [45]:
df['Schooling'].unique()

array([10.1, 10. ,  9.9,  9.8,  9.5,  9.2,  8.9,  8.7,  8.4,  8.1,  7.9,
        6.8,  6.5,  6.2,  5.9,  5.5, 14.2, 13.3, 12.5, 12.2, 12. , 11.6,
       11.4, 10.8, 10.9, 10.7, 10.6, 14.4, 14. , 13.6, 13.1, 12.6, 12.3,
       11.7, 11.5, 11.1, 10.3,  9.4,  9. ,  8.5,  7.7,  7.2,  6.4,  5.1,
        4.6, 13.9, 13.8, 14.1, 14.5, 14.7,  0. , 17.3, 17.2, 17.1, 16.8,
       16.5, 16.3, 16.1, 16.4, 15.6, 15. , 12.7, 11.9, 11.2, 20.4, 20.3,
       20.1, 19.8, 19.5, 19.1, 19. , 20.7, 20.6, 20.5, 15.9, 15.7, 15.4,
       15.3, 15.1, 15.2, 14.9, 15.5, 11.8, 11. , 10.4, 12.4, 12.1, 13.7,
       13.5, 13.2, 10.2,  8.6,  8.2,  7.5,  7.3, 15.8, 14.8, 14.6, 16.6,
       16.2, 18.8, 18.6, 18.2, 18. , 12.8, 12.9,  9.3,  9.1,  6.6, 10.5,
        9.6,  8.8,  8. ,  7.6, 14.3, 13.4,  6.7,  6.3,  5.4,  4.9,  4.7,
        4.3,  3.9,  3.8,  3.6,  3.5,  3.4,  5.6,  5.2,  4.4,  4.5,  nan,
       11.3,  9.7,  8.3,  7.1,  6.9,  6. ,  5.7,  5.3, 13. , 17.6, 17.7,
       16. , 19.2, 18.7, 18.4, 16.9, 16.7,  5. ,  4. ,  3.7,  3.3,  2.9,
        5.8, 17. , 18.3, 18.1,  7.8,  7. ,  4.8,  7.4, 17.9, 18.5, 17.5,
        6.1, 19.3, 19.7, 18.9, 17.4,  4.2,  3.1,  3. ,  2.8])

In [ ]:
df['BMI']=df[' BMI ']

In [55]:
a=['Life expectancy ','Adult Mortality','Alcohol','Hepatitis B','GDP','Polio','Schooling','Diphtheria ']
b=[' BMI ','Total expenditure','Population',' thinness  1-19 years',' thinness 5-9 years','Income composition of resources']
for i in a:
    df[i].fillna(df[i].mode()[0],inplace=True)
for i in b:
    df[i].fillna(df[i].mean(),inplace=True)

In [56]:
df.isnull().sum()

Country                            0
Year                               0
Status                             0
Life expectancy                    0
Adult Mortality                    0
infant deaths                      0
Alcohol                            0
percentage expenditure             0
Hepatitis B                        0
Measles                            0
 BMI                               0
under-five deaths                  0
Polio                              0
Total expenditure                  0
Diphtheria                         0
 HIV/AIDS                          0
GDP                                0
Population                         0
 thinness  1-19 years              0
 thinness 5-9 years                0
Income composition of resources    0
Schooling                          0
dtype: int64

In [59]:
X=df.drop('Life expectancy ',axis=1)
y=df['Life expectancy ']

In [60]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25)

In [62]:
from sklearn.model_selection import KFold
fold=KFold(random_state=7,n_splits=100,shuffle=True)

In [64]:
from sklearn.ensemble import GradientBoostingRegressor
model=GradientBoostingRegressor(n_estimators=10,learning_rate=0.1,random_state=42)

In [65]:
from sklearn.model_selection import cross_val_score
cv=cross_val_score(model,X_train,y_train,cv=fold)
for i in range(len(cv)):
    print("model:",i,'accuracy:',cv[i])

model: 0 accuracy: 0.8419802830796402
model: 1 accuracy: 0.8099476630537148
model: 2 accuracy: 0.6483451251614774
model: 3 accuracy: 0.7733329620589701
model: 4 accuracy: 0.7386663954315853
model: 5 accuracy: 0.8282615259840813
model: 6 accuracy: 0.760580380339362
model: 7 accuracy: 0.7769437861259423
model: 8 accuracy: 0.7827684732951734
model: 9 accuracy: 0.6896243246871469
model: 10 accuracy: 0.7971776721005224
model: 11 accuracy: 0.7101006981212392
model: 12 accuracy: 0.7340258014943706
model: 13 accuracy: 0.6403750813628086
model: 14 accuracy: 0.6905548152646944
model: 15 accuracy: 0.7327144411785133
model: 16 accuracy: 0.7321288904888175
model: 17 accuracy: 0.7940513302351313
model: 18 accuracy: 0.768000555617907
model: 19 accuracy: 0.7191072027721921
model: 20 accuracy: 0.8306934570537725
model: 21 accuracy: 0.753787257230827
model: 22 accuracy: 0.7261641700126387
model: 23 accuracy: 0.833195590059522
model: 24 accuracy: 0.641757898381507
model: 25 accuracy: 0.7893006559937058
model: 26 accuracy: 0.7116347442085607
model: 27 accuracy: 0.7090662562364322
model: 28 accuracy: 0.7092151737203485
model: 29 accuracy: 0.8052956194533722
model: 30 accuracy: 0.7661095485887248
model: 31 accuracy: 0.5367864227863894
model: 32 accuracy: 0.7978556582543348
model: 33 accuracy: 0.7437425335529084
model: 34 accuracy: 0.7574589578268076
model: 35 accuracy: 0.7133518404253335
model: 36 accuracy: 0.7621781852043391
model: 37 accuracy: 0.83613837102336
model: 38 accuracy: 0.7691461002365321
model: 39 accuracy: 0.7863741452422953
model: 40 accuracy: 0.6938604306118354
model: 41 accuracy: 0.7786722341938008
model: 42 accuracy: 0.8081064824905106
model: 43 accuracy: 0.30077561977555956
model: 44 accuracy: 0.7748128859168165
model: 45 accuracy: 0.698423173353375
model: 46 accuracy: 0.7938274613113481
model: 47 accuracy: 0.6707621832642704
model: 48 accuracy: 0.7888032092842828
model: 49 accuracy: 0.7444488802953324
model: 50 accuracy: 0.7204267357579315
model: 51 accuracy: 0.7525124012644018
model: 52 accuracy: 0.8543397748919886
model: 53 accuracy: 0.7848062388349242
model: 54 accuracy: 0.7859207146975182
model: 55 accuracy: 0.7352629131700743
model: 56 accuracy: 0.7345160685556067
model: 57 accuracy: 0.8231987214873995
model: 58 accuracy: 0.8279959618433423
model: 59 accuracy: 0.7792352030776046
model: 60 accuracy: 0.7719481225416147
model: 61 accuracy: 0.723193947232693
model: 62 accuracy: 0.7762613065407935
model: 63 accuracy: 0.6713140905557307
model: 64 accuracy: 0.7344061544432118
model: 65 accuracy: 0.7837035095956388
model: 66 accuracy: 0.7743465823444664
model: 67 accuracy: 0.7657326341859915
model: 68 accuracy: 0.7498741374748918
model: 69 accuracy: 0.8236456672752621
model: 70 accuracy: 0.7134135690773894
model: 71 accuracy: 0.7588640838223799
model: 72 accuracy: 0.810307676577533
model: 73 accuracy: 0.7947983818242093
model: 74 accuracy: 0.7487170546644413
model: 75 accuracy: 0.7752183268096419
model: 76 accuracy: 0.6852988822512205
model: 77 accuracy: 0.7614305235563059
model: 78 accuracy: 0.78116438186332
model: 79 accuracy: 0.8449839441715887
model: 80 accuracy: 0.7132804802243964
model: 81 accuracy: 0.7322199530157086
model: 82 accuracy: 0.6653540019349304
model: 83 accuracy: 0.6803006607469686
model: 84 accuracy: 0.7531944122189163
model: 85 accuracy: 0.8114640778523203
model: 86 accuracy: 0.777604169716219
model: 87 accuracy: 0.7824106641407464
model: 88 accuracy: 0.722517546391704
model: 89 accuracy: 0.7269353339235736
model: 90 accuracy: 0.6856812966317432
model: 91 accuracy: 0.8082847887739719
model: 92 accuracy: 0.7213287607465455
model: 93 accuracy: 0.621242099411109
model: 94 accuracy: 0.760428264603016
model: 95 accuracy: 0.7760521859096955
model: 96 accuracy: 0.6786103295504697
model: 97 accuracy: 0.8302094145934356
model: 98 accuracy: 0.7087911717361173
model: 99 accuracy: 0.7359170590739514

In [67]:
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
model.fit(X_train,y_train)
y_pred=model.predict(X_test)
print(r2_score(y_test,y_pred))
print(mean_squared_error(y_test,y_pred))
print(np.sqrt(mean_squared_error(y_test,y_pred)))
print(mean_absolute_error(y_test,y_pred))

0.7585838458059391
21.941549413822514
4.684180762291579
3.6155493498913542

In [ ]:
|}